### ISSUE TITLE
app not running on local  host

### ISSUE THREAD

**Issue by vaidyashubham** [AmitXShukla/Online-School-Management-App-Angular-Firebase#1]
when i serve app it gives me "@copyright 2019 Amit.LA   https://github.com/AmitXShukla".

**Comment by AmitXShukla** [comment]
I assume, there is no other compilation error. Please check your app.component.html for has router-outlet and app.routing file if routes are setup correctly.
Please include a screen-shot of these files and console if you can.

**Comment by vaidyashubham** [comment]
![Untitled](https://user-images.githubusercontent.com/42665352/60380313-54663380-9a61-11e9-9bda-7e7a77c9d1ab.png)
![Untitled1](https://user-images.githubusercontent.com/42665352/60380314-54feca00-9a61-11e9-8f7a-a514c33edc21.png)
![Untitled2](https://user-images.githubusercontent.com/42665352/60380315-54feca00-9a61-11e9-96d5-b22c1d5f2ab3.png)

**Comment by AmitXShukla** [comment]
Thanks, You should look at ng serve console log as well. However, browser log is very clear, API key is invalid. that means, your FireBase is NOT setup correctly.
Please watch the video and update your environment -> environment.ts FireBase settings.
firebase : {
    apiKey: "         ",
    authDomain: "      ",
    databaseURL: "   ",
    projectId: " ",
    storageBucket: "  ",
    messagingSenderId: " "
  }

**Comment by vaidyashubham** [comment]
But ngserve is running fine there is no problem with that.

**Comment by rajatpal94** [comment]
Thank you, this is very useful application, but in settings page, after login i fetch this error..

ERROR TypeError: Cannot read property '_id' of undefined
    at SwitchMapSubscriber.project (backend.service.ts:91)
    at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._next (switchMap.js:35)
    at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:41)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
    at angularfire2.js:49
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)

**Comment by AmitXShukla** [comment]
> 
> 
> Thank you, this is very useful application, but in settings page, after login i fetch this error..
> 
> ERROR TypeError: Cannot read property '_id' of undefined
> at SwitchMapSubscriber.project (backend.service.ts:91)
> at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._next (switchMap.js:35)
> at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
> at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:41)
> at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
> at angularfire2.js:49
> at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
> at Object.onInvoke (core.js:17299)
> at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
> at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)

@rajatpal94 I will fork this repository and look into this issue. I believe, this may be due to Angular Version conflict. You be on latest Angular version (8) and this repo is on Angular 7.2.14 & 8.0.0 rc.0.
I will upgrade this repo soon.
