### ISSUE TITLE
firebase database tables

### ISSUE THREAD

**Issue by cirilinfo** [AmitXShukla/Online-School-Management-App-Angular-Firebase#15]
Hi, I have used the firebase roles but tables not generate. How to generate tables in firebase.

**Comment by AmitXShukla** [comment]
You will need to create only one collection SMS_ROLES so that your app can authenticate users against roles.
rest of the collections will automatically be created as your access app write data into database.
Please look into screenshots.
https://medium.com/@Amit_Shukla/online-school-management-app-8e58449427c0

**Comment by cirilinfo** [comment]
Hi, i've done all the necessary configuration but i am unable to singin or login the application. The app is running in local but problem in login. find my screens and let me know the solution.   

![db](https://user-images.githubusercontent.com/63291604/78819003-2865de80-79f3-11ea-8ccd-590523a8cd6d.PNG)
![en](https://user-images.githubusercontent.com/63291604/78819008-2a2fa200-79f3-11ea-8545-610f7ffea3a5.PNG)
![login](https://user-images.githubusercontent.com/63291604/78819011-2a2fa200-79f3-11ea-8056-3e7278b38625.PNG)
![rules](https://user-images.githubusercontent.com/63291604/78819013-2ac83880-79f3-11ea-90f3-edeb7029fa81.PNG)
![signup](https://user-images.githubusercontent.com/63291604/78819015-2b60cf00-79f3-11ea-9ffc-7e95c1175a07.PNG)

**Comment by cirilinfo** [comment]
Hi, i have log in the app but unable to do the settings find my screenshot and let me know the solutions.
![settings](https://user-images.githubusercontent.com/63291604/78822741-39195300-79f9-11ea-8e4d-23c8a64a8834.PNG)

**Comment by AmitXShukla** [comment]
can you try changing this collection (as mentioned below) and see if the solves the issue, 
and if does, please try adding conditions back one at a time and see which condition is failing.

-----AFTER
match /SMS_USERS/{document} {
allow create: if true;
allow update: if true;
allow read: if true;
}
--------------------BEFORE
match /SMS_USERS/{document} {
allow create: if exists(/databases/$(database)/documents/SMS_ROLES/$(request.resource.data.secretKey))
&& get(/databases/$(database)/documents/SMS_ROLES/$(request.resource.data.secretKey)).data.role == request.resource.data.role;
allow update: if exists(/databases/$(database)/documents/SMS_ROLES/$(request.resource.data.secretKey))
&& get(/databases/$(database)/documents/SMS_ROLES/$(request.resource.data.secretKey)).data.role == request.resource.data.role
&& isDocOwner();
allow read: if isSignedIn() && isDocOwner();
}

**Comment by cirilinfo** [comment]
same issue 

![db_NEW](https://user-images.githubusercontent.com/63291604/78858721-e2d50000-7a4a-11ea-8e6f-6cb4361dc8b4.PNG)
![settings](https://user-images.githubusercontent.com/63291604/78858738-e9fc0e00-7a4a-11ea-84ea-e0d43610c6fc.PNG)

**Comment by AmitXShukla** [comment]
why you have 
match /SMS_USERS/{document} rules twice
line #7 and line #12
You need to keep only one set (means, get rid of line #12 through #19)

**Comment by cirilinfo** [comment]
i have removed one set but still facing the same issue 
![db_NEW](https://user-images.githubusercontent.com/63291604/78894049-023f4d80-7a8a-11ea-983d-b49b03da1830.PNG)

**Comment by AmitXShukla** [comment]
I will download this repository and run this later this week.
Please expect a fix by Monday.
Also, FYI - I have a new series coming up this week, where I discuss how to setup Firebase rules and Role based security in detail.
Please subscribe https://www.youtube.com/amitshukla_ai
and give a star to this repository
https://github.com/AmitXShukla/ERP-Apps-CRM-Cloud-Angular_FireStore

**Comment by cirilinfo** [comment]
@AmitXShukla any update on the firebase ROLE issue.

**Comment by AmitXShukla** [comment]
Sorry to keep you waiting, I'm busy with other project.

For now, just update every thing to true (not recommended approach for sure) and I will update these rules later this week.

allow create: if true;
allow update: if true;
allow read: if true;

**Comment by cirilinfo** [comment]
@AmitXShukla i have set everything true but still having same issues.

**Comment by AmitXShukla** [comment]
Can you please include some screenshots of errors from web and terminal console. I have this repository open, will fix it all at once.

**Comment by cirilinfo** [comment]
@AmitXShukla  find the screenshots for your reference

![fb](https://user-images.githubusercontent.com/63291604/79892103-d93a8900-83b6-11ea-9d7c-d2f8cfe2101e.PNG)
![pe](https://user-images.githubusercontent.com/63291604/79892113-db9ce300-83b6-11ea-951c-60cc5a5a7d4f.PNG)
![pe1](https://user-images.githubusercontent.com/63291604/79892121-de97d380-83b6-11ea-8375-cb9156c40c7c.PNG)

**Comment by AmitXShukla** [comment]
Temporary fix for You is,
Set everything to true 
In your collections, only user roles is true, rest aren’t.

To learn more about how to setup rules, please watch this video 

https://youtu.be/AuZejtI7uU8

I’ll fix this repository once I finish my current project.

**Comment by AmitXShukla** [comment]
update this repo to latest Angular 9.1.4 version, Please download and re-install this app

**Comment by AmitXShukla** [comment]
update this repo to v 11.0
