### ISSUE TITLE
facebook authentication not working

### ISSUE THREAD

**Issue by sreyashi-123** [AmitXShukla/Online-School-Management-App-Angular-Firebase#17]
I have created an app in developers facebook site and from there i have copied  the app id and app secret key and pasted it in authentication page of the firebase.Also i have COPIED the Oth redirect Url from firebase and pasted it under the products section under facebook settings page.Still after validating the facebook option in the app it is not redirecting to the update profle page instead it is coming back to the initial login page.Can you mention where i am going wrong. 
![image](https://user-images.githubusercontent.com/63251445/79063073-0e5f2100-7cbd-11ea-85fe-a54df6641cef.png)

**Comment by sreyashi-123** [comment]
Basic settings page in fb developers site for your reference.
![image](https://user-images.githubusercontent.com/63251445/79063404-32236680-7cbf-11ea-9135-23a8b4ca2eb3.png).Can you check where m i going wrong.As far as code is concerned i have not changed that from yours.

**Comment by AmitXShukla** [comment]
Did you copy these settings over your database Firebase -> Authentication-> Sign-in methods -> Facebook -> enable

**Comment by sreyashi-123** [comment]
Yes I did copy
