### ISSUE TITLE
I have pasted the rules in firebase database but no data is showing in data tab

### ISSUE THREAD

**Issue by Pradeeptamegatech** [AmitXShukla/Online-School-Management-App-Angular-Firebase#2]
Hi ,
I have installed the app in my local machine and its running okay then I  pasted the rules but i don't see any collections in my data tab of my firebase database. so i could't logging into the system.
Should i create it manually one by one or any script you will provide to us which i need to run . Please help.
![image](https://user-images.githubusercontent.com/39087897/65145469-46f49000-da37-11e9-8520-9fdf56c6e4c1.png)

![image](https://user-images.githubusercontent.com/39087897/65145323-ef562480-da36-11e9-82dd-a3927a7cde19.png)

**Comment by AmitXShukla** [comment]
Yes, you will need to create at-least one Firebase collection for roles as shown in video, otherwise app will not be able to authorize your role.
