### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sobhansai03** [AmitXShukla/Online-School-Management-App-Angular-Firebase#20]
Can you please update it to latest angular cli :)

**Comment by AmitXShukla** [comment]
I acknowledge, will update this repository soon.
-Amit
________________________________

**Comment by AmitXShukla** [comment]
sorry for the delay, I was waiting for Angular 11 release, will update this repository by Nov 30.

**Comment by AmitXShukla** [comment]
update this repo to v 11.0
