### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by iffandsbiyu123** [AmitXShukla/Online-School-Management-App-Angular-Firebase#21]
is there any other way, other than to restore the legacy node?
because on my device I can't install the legacy version of the node

**Comment by AmitXShukla** [comment]
Sorry if I misunderstood your question, if you know your legacy node version, you can always download/install that version.

**Comment by iffandsbiyu123** [comment]
Maybe the meaning of my question, is your web application compatible with the latest version of node / npm and angular?

**Comment by AmitXShukla** [comment]
yes,
This app will work with Latest NodeJS and latest Angular release.

**Comment by iffandsbiyu123** [comment]
hi mr, my status student in school, i am no have money for subscribe cause
pandemy, but i need this source code for my task in school, can u help me
mr?

Pada tanggal Rab, 17 Feb 2021 pukul 13.23 Amit Shukla <
notifications@github.com> menulis:

**Comment by iffandsbiyu123** [comment]
i want u can help me for giving role admin?, cause i am really need this
app, but iam no money for subscribe, sorry in advance sir
can u help me please


Pada tanggal Kam, 18 Feb 2021 pukul 01.57 iffands biyu <iffandsb@gmail.com>
menulis:

**Comment by iffandsbiyu123** [comment]
i am a beginner want to learn angular sir


Pada tanggal Kam, 18 Feb 2021 pukul 02.01 iffands biyu <iffandsb@gmail.com>
menulis:

**Comment by AmitXShukla** [comment]
Thanks for reaching out Pada tanggal Kam.
You don't need any money to learn Angular or subscribe me either.
all of my projects are free forever.

Unfortunately, I don't have any beginner tutorial series for Angular projects, so please google or watch YouTube for beginner's tutorials, Once you have beginner understanding of Angular, please follow me over YouTube.

However, If you are interested in Flutter development, I have beginner's level series, which you should explore.
https://www.youtube.com/playlist?list=PLp0TENYyY8lGaU3m8GaO4hW19SJR5tjlT

**Comment by iffandsbiyu123** [comment]
Thank you, I will check it out.

Kam, 18 Feb 2021 pukul 04.14 Amit Shukla <notifications@github.com> menulis:
