### ISSUE TITLE
Unable to install Angular

### ISSUE THREAD

**Issue by prugit1** [AmitXShukla/Online-School-Management-App-Angular-Firebase#22]
I
![Capture1](https://user-images.githubusercontent.com/72058044/108103308-c6184880-70af-11eb-98e9-b161cd62bb41.PNG)
 tried installing angular on my PC but was unable to install it. I have attached the screenshot of the error. Kindly help me with this.

**Comment by AmitXShukla** [comment]
These are just warning, looks like you already have Angular installed.
Run 
> ng version

**Comment by prugit1** [comment]
Thank you, sir. Issue resolved.
