### ISSUE TITLE
Unable to open a server

### ISSUE THREAD

**Issue by prugit1** [AmitXShukla/Online-School-Management-App-Angular-Firebase#23]
I have installed Angular 11.0.0 and copied all the source files obtained from this git repository and followed the steps mentioned in your youtube video. But I am getting an error while starting the server. I have attached the screenshot for your reference. Kindly help me.
![Capture11](https://user-images.githubusercontent.com/72058044/108164044-11654200-7116-11eb-883b-4ee3dc4d03b3.PNG)

**Comment by AmitXShukla** [comment]
something wrong with your angular.json

did you copy over mine ? or it was there before.
try changing project name or some settings in your angular.json file to match your project

#if it doesn't work, please attach your angular.json and package.json
and I'll debug this tomorrow.

**Comment by prugit1** [comment]
Thank you for your reply. I have just copied your files without making any changes. I have attached the angular.json and package.json files here. Please help me out in solving the issue.
[json.zip](https://github.com/AmitXShukla/Online-School-Management-App-Angular-Firebase/files/5993697/json.zip)

**Comment by AmitXShukla** [comment]
Thanks
please expect an update tomorrow.

**Comment by AmitXShukla** [comment]
fixed now,
please update angular.json line 2 to
"version": 1,
