### ISSUE TITLE
Firestore collections

### ISSUE THREAD

**Issue by shahiddgk** [AmitXShukla/Online-School-Management-App-Angular-Firebase#24]
Hello Sir,
             This seems very amazing app. I am super excited. But it seems collection of firestore is missing. I have setup roles. Can you please give me collections.

**Comment by AmitXShukla** [comment]
Thanks, I believe, once you start using app, it will auto create collections after data entry.
Please watch these first videos for more details.

https://www.youtube.com/playlist?list=PLp0TENYyY8lHnfxOOzZ_hTnPF8Hh3eKDo
