### ISSUE TITLE
port forwardingin docker

### ISSUE THREAD

**Issue by Rahul-012** [AmitXShukla/Online-School-Management-App-Angular-Firebase#25]
Hi Amit,

Why this application is not working when i do port forwarding in docker , with the local host i can able to run

**Comment by AmitXShukla** [comment]
I would create a web server on docker and deploy it like a web app.

This is Angular Firebase app, easiest option for you to run it over cloud is, deploy it on Firebase hosting.
Please see, video #4 in this series.
https://www.youtube.com/playlist?list=PLp0TENYyY8lGM358Jk86Y_QKgOCe4hID6
