### ISSUE TITLE
works only on localhhost

### ISSUE THREAD

**Issue by Rahul-012** [AmitXShukla/Online-School-Management-App-Angular-Firebase#26]
Hi Amit,

This application is works only on local host , how can i  run it to my private IP

**Comment by AmitXShukla** [comment]
This is Angular Firebase app, easiest option for you to run it over cloud is, deploy it on Firebase hosting.
Please see, video #4 in this series.
https://www.youtube.com/playlist?list=PLp0TENYyY8lGM358Jk86Y_QKgOCe4hID6
