### ISSUE TITLE
Cannot find attendance feature

### ISSUE THREAD

**Issue by 133usr** [AmitXShukla/Online-School-Management-App-Angular-Firebase#28]
According to the read me there should be an attendance feature
However I went thoroughly through the app but I couldn't find the attendance feature can you please help me with that

**Comment by AmitXShukla** [comment]
Mobile Attendance Picture, GPS Tracking -Angular Firebase App

https://www.youtube.com/playlist?list=PLp0TENYyY8lHiTISr7IhQi0iu7f1op9ME


create app - COVID Contact Tracing, Visitor Management, Mobile Attendance Angular Firebase Project

https://youtu.be/MkV413X2Kmw


----------


-Amit
________________________________
From: 133usr ***@***.***>
Sent: Wednesday, January 18, 2023 10:38:21 PM
To: AmitXShukla/Online-School-Management-App-Angular-Firebase ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AmitXShukla/Online-School-Management-App-Angular-Firebase] Cannot find attendance feature (Issue #28)


According to the read me there should be an attendance feature
However I went thoroughly through the app but I couldn't find the attendance feature can you please help me with that
