### ISSUE TITLE
unable to find collection in firebase

### ISSUE THREAD

**Issue by sameer7979** [AmitXShukla/Online-School-Management-App-Angular-Firebase#3]
[Copied and pasted settings in env file.docx](https://github.com/AmitXShukla/Online-School-Management-App-Angular-Firebase/files/3748149/Copied.and.pasted.settings.in.env.file.docx)

**Comment by AmitXShukla** [comment]
you are right, SMS_ROLES doesn't exist, you will need to create one new collection (SMS_ROLES) and then create 5-6 documents inside it. Please see last 2 screenshots from this link.

https://medium.com/@Amit_Shukla/online-school-management-app-8e58449427c0
