### ISSUE TITLE
I have converted the school management system from firebase to mongodb

### ISSUE THREAD

**Issue by haidermlk** [AmitXShukla/Online-School-Management-App-Angular-Firebase#8]
![badreq](https://user-images.githubusercontent.com/44856950/74122082-bc7e1a00-4beb-11ea-8f04-1fce654e812d.png)

**Comment by AmitXShukla** [comment]
This issue is either related to setup CORS or NODEJS Server not configured properly, Closing this issue now, please re-open if is still not working for you.
